
-- (chinese, chinese_variation, jyutping, pinyin, english, category, subcategory, subcategory2, priority)
-- ("", NULL, "", "", "", "", "", NULL, NULL), 
INSERT INTO vocabulary VALUES
  ("餵", NULL, "wai3", "wèi", "to feed (an animal or person)", "Verbs", NULL, NULL, NULL), 
  ("保護", NULL, "bou2 wu6", "bǎo hù", "to protect, to safeguard, to preserve", "Verbs", NULL, NULL, NULL), 
  ("總結", NULL, "zung2 git3", "zǒng jié", "summary", "Nouns", "Media", "Literature", NULL), 
  ("總結", NULL, "zung2 git3", "zǒng jié", "to summarize, to sum up", "Verbs", NULL, NULL, NULL), 
  ("情節", NULL, "cing4 zit4", "qíng jié", "plot, story, synopsis", "Nouns", "Media", "Literature", NULL), 
  ("乞求", NULL, "hat1 kau4", "qǐ qiú", "to beg, to implore, to beseech", "Verbs", NULL, NULL, NULL), 
  ("唔好", NULL, "m4 hou2", "wú hǎo", "don't", "Other", NULL, NULL, NULL), 
  ("離開", NULL, "lei4 hoi1", "lí kāi", "to leave, to depart", "Verbs", NULL, NULL, NULL), 
  ("反正", NULL, "faan2 zing3", "fǎn zheng", "anyway, in any case", "Adverbs", NULL, NULL, NULL), 
  ("生活費", NULL, "sang1 wu6 fai3", "shēng huó fèi", "cost of living, living expenses", "Nouns", "Economics", NULL, NULL), 
  ("註釋", NULL, "zyu3 sik1", "zhù shì", "annocation, comment", "Nouns", NULL, NULL, NULL), 
  ("圖畫", NULL, "tou4 waa6", "tú huà", "picture, drawing", "Nouns", "Art", NULL, NULL), 
  ("雕塑", NULL, "diu1 sou3", "diāo sù", "statue, sculpture", "Nouns", "Art", NULL, NULL), 
  ("陶器", NULL, "tou4 hai3", "táo qì", "pottery, earthenware", "Nouns", "Art", NULL, NULL), 
  ("攝影", NULL, "sip3 jing2", "shè yǐng", "photography, shooting (of a film)", "Nouns", "Art", NULL, NULL), 
  ("水彩", NULL, "sui2 coi2", "shuǐ cǎi", "watercolors", "Nouns", "Art", NULL, NULL), 
  ("油漆", NULL, "jau4 cat1", "yóu qī", "oil paint", "Nouns", "Art", NULL, NULL), 
  ("噴漆", NULL, "pan3 cat1", "pēn qī", "spray paint", "Nouns", "Art", NULL, NULL), 
  ("畫筆", NULL, "waa6 bat1", "huà bǐ", "paintbrush", "Nouns", "Art", NULL, NULL), 
  ("畫布", NULL, "waa2 bou3", "huà bù", "canvas (for painting)", "Nouns", "Art", NULL, NULL), 
  ("草圖", NULL, "cou2 tou2", "cǎo tú", "sketch, rough drawing", "Nouns", "Art", NULL, NULL), 
  ("墨水", NULL, "mak6 seoi2", "mò shuǐ", "ink", "Nouns", "Art", NULL, NULL), 
  ("書法", NULL, "syu1 faat3", "shū fǎ", "calligraphy", "Nouns", "Art", NULL, NULL), 
  ("鑲嵌藝術", NULL, "soeng1 ham3 ngai6 seot6", "xiāng​ qiàn yì​ shù", "mosaic (lit. tiling art)", "Nouns", "Art", NULL, NULL), 
  ("想象", NULL, "soeng2 zoeng6", "xiǎng​ xiàng", "imagination", "Nouns", "Art", NULL, NULL), 
  ("想象", NULL, "soeng2 zoeng6", "xiǎng​ xiàng", "to imagine, to envision", "Verbs", NULL, NULL, NULL), 
  ("", NULL, "", "", "", "Nouns", "Art", NULL, NULL), 
  ("", NULL, "", "", "", "Nouns", "Art", NULL, NULL), 
  ("", NULL, "", "", "", "Nouns", "Art", NULL, NULL),
  ("無用", NULL, "mou4 jung6", "wú​ yòng", "useless, worthless", "Adjectives", NULL, NULL, NULL), 
  ("概率", NULL, "koi3 leot6", "gài lǜ", "probability, odds", "Nouns", "Mathematics", "Statistics", NULL), 
  ("分佈", NULL, "fan1 bou3", "fēn bù", "distribution", "Nouns", "Mathematics", "Statistics", NULL), 
  ("抽樣", NULL, "cau1 jeong6", "chōu yàng", "sampling", "Nouns", "Mathematics", "Statistics", NULL), 
  ("異常值", NULL, "ji6 soeng4 zik6", "yì​ cháng zhí", "outlier (lit. unusual value)", "Nouns", "Mathematics", "Statistics", NULL), 
  ("離㪊值", NULL, "lei4 kwan4 zik6", "lí qún zhí", "outlier", "Nouns", "Mathematics", "Statistics", NULL), 
  ("散點圖", NULL, "saan2 dim2 tou4", "sǎn diǎn tú", "scatter plot", "Nouns", "Mathematics", "Statistics", NULL), 
  ("標準差", NULL, "biu1 zeon2 caa1", "biāo zhǔn chā", "standard deviation", "Nouns", "Mathematics", "Statistics", NULL), 
  ("條形圖", NULL, "tiu4 jing4 tou4", "tiáo xíng tú", "bar chart", "Nouns", "Mathematics", "Statistics", NULL), 
  ("圓形圖", NULL, "jyun4 jing4 tou4", "yuán xíng tú", "pit chart", "Nouns", "Mathematics", "Statistics", NULL), 
  ("餅圖", NULL, "beng2 tou4", "bǐng tú", "pie chart", "Nouns", "Mathematics", "Statistics", NULL), 
  ("數據可視化", NULL, "sou3 geoi3 ho2 si6 faa3", "shù​ jù kě​ shì​ huà", "data visualization", "Nouns", "Mathematics", "Statistics", NULL), 
  ("", NULL, "", "", "", "Nouns", "Mathematics", "Statistics", NULL), 
  ("", NULL, "", "", "", "Nouns", "Mathematics", "Statistics", NULL), 
  ("", NULL, "", "", "", "Nouns", "Mathematics", "Statistics", NULL), 
  ("", NULL, "", "", "", "Nouns", "Mathematics", "Statistics", NULL), 
  ("孤獨", NULL, "gu1 duk6", "gū dú", "loneliness, lonely", "Nouns", "Psychology", NULL, NULL), 
  ("園林", NULL, "jyun4 lam4", "yuán lín", "garden, chinese landscape garden", "Nouns", "Gardening", NULL, NULL), 
  ("果樹", NULL, "gwo2 syu6", "guǒ shù", "fruit tree", "Nouns", "Gardening", NULL, NULL), 
  ("果園", NULL, "gwo2 jyun4", "guǒ yuán", "orchard", "Nouns", "Gardening", NULL, NULL), 
  ("", NULL, "", "", "", "Nouns", "Gardening", NULL, NULL), 
  ("", NULL, "", "", "", "Nouns", "Gardening", NULL, NULL), 
  ("", NULL, "", "", "", "Nouns", "Gardening", NULL, NULL), 
  ("自然", NULL, "zi6 jin4", "zì rán", "nature", "Nouns", "Biology", NULL, NULL), 
  ("功效", NULL, "gung1 haau6", "gōng xiào", "efficiency, efficacy", "Nouns", NULL, NULL, NULL), 
  ("效率", NULL, "haau6 leot6", "xiào lǜ", "efficiency, productiveness", "Nouns", NULL, NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL), 
  ("", NULL, "", "", "", "", "", NULL, NULL)
;
